### ISSUE TITLE
Thaumcraft dependency crash.

### ISSUE THREAD

**Issue by hjake123** [pixlepix/Aura-Cascade#38] opened 2015-03-16 14:47 UTC
When attempting to run without Thaumcraft installed, this crash occurs on start-up. With Thaumcraft installed (a different instance), it works just fine. The relevant (I think) part of the crash log is here:
 
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/ThaumcraftApi
at pixlepix.auracascade.main.compat.TCCompat.postInit(TCCompat.java:13)
at pixlepix.auracascade.main.CommonProxy.postInit(CommonProxy.java:96)
at pixlepix.auracascade.main.ClientProxy.postInit(ClientProxy.java:41)
at pixlepix.auracascade.AuraCascade.postInit(AuraCascade.java:38)

I assume this is a bug, as TC is not mentioned as a dependency, and it crashes rather giving that forge screen. Here is the full log:
https://docs.google.com/document/d/1RKKACa8k7B78uwsS2uKpNhjeWUWwTGrquhZwINCmr5I/edit?usp=sharing

**Comment by pixlepix** [comment] 2015-03-17 00:51
Duplicate of #35, it will be in the next update. Taking a bit longer than I wanted because I'm working on a new feature.

**Closed by pixlepix** 2015-03-17 00:51 UTC
